export enum AppRoutings {
  LogIn = "/login",
  UserListing = "/admin/user",
  CMSPageListing = "/admin/cms",
  MissionListing = "/admin/missions",
  MissionAdd = "/admin/missions/add",
  MissionEdit = "/admin/missions/edit/",
  ThemeListing = "/admin/mission-themes",
  ThemeAdd = "/admin/mission-themes/add",
  ThemeEdit = "/admin/mission-themes/edit/",
  SkillListing = "/admin/mission-skills",
  ApplicationListing = "/admin/mission-applications",
  StoryListing = "/admin/stroies",
  BannerListing = "/admin/banner",
  BannerAdd = "/admin/banner/add",
  BannerEdit = "/admin/banner/edit/",
  ResetPassword = "/reset-password",
  ForgotPassword = "/forgot-password",
  CMSAdd = "/admin/cms/add",
  CMSEdit = "/admin/cms/edit/",
  CMSListing = "/admin/cms",
  Registation = "/register",
}
